language: node_js

branches:
  except:
      #- /^(?i:feature)-.*$/
      #- /^(?i:release)-.*$/

node_js:
  - 'node'

notifications:
  email:
      on_success: never
      on_failure: never
  slack:
      on_failure: change
      on_success: change
      rooms:
          - openbase-org:vGz7LO4CvGoGMneYkEm3ON7E#build
          #- openbase-org:vGz7LO4CvGoGMneYkEm3ON7E#jul
